import type { GameMeta } from "@/types/games";

/**
 * Central game registry for the Library feature.
 * Mirrors PlayLab's src/games/registry.ts — add/remove games in both places.
 *
 * Each entry maps to a PlayLab route: ${NEXT_PUBLIC_PLAYLAB_URL}${route}
 */
export const GAMES: readonly GameMeta[] = [
  {
    id: "letter-tracing",
    category: "literacy",
    title: "ABC",
    description: "Trace letters & numbers",
    glyph: "✏️",
    route: "/play/letter-tracing",
    colors: { bg: "#DDD5F5", border: "#A882E8", text: "#7C5CBF" },
  },
  {
    id: "jungle-spy",
    category: "literacy",
    title: "Jungle Spy",
    description: "Find the hiding letters",
    glyph: "🔍",
    route: "/play/jungle-spy",
    colors: { bg: "#C8F0D8", border: "#66CC94", text: "#3DAA72" },
  },
  {
    id: "letter-hunt",
    category: "literacy",
    title: "Letter Hunt",
    description: "Find the matching letters",
    glyph: "🅰️",
    route: "/play/letter-hunt",
    colors: { bg: "#FFE1EC", border: "#FF8FA3", text: "#D14D82" },
  },
  {
    id: "magnet-match",
    category: "literacy",
    title: "Magnet Match",
    description: "Alphabet soup with the chef",
    glyph: "🍲",
    route: "/play/magnet-match",
    colors: { bg: "#FBE7A2", border: "#E8B33D", text: "#8A5A2E" },
  },
  {
    id: "dino-dig",
    category: "literacy",
    title: "Dino Dig",
    description: "Feed dinos & bridge the river",
    glyph: "🦕",
    route: "/play/dino-dig",
    colors: { bg: "#CFF1F4", border: "#00C4CC", text: "#0A1A3A" },
  },
  {
    id: "letter-treats",
    category: "literacy",
    title: "Letter Treats",
    description: "Phonics in Candy World",
    glyph: "🧁",
    route: "/play/letter-treats",
    colors: { bg: "#FFD3E4", border: "#FF9EC4", text: "#C2417A" },
  },
  {
    id: "feed-the-shark",
    category: "literacy",
    title: "Feed the Shark",
    description: "Match big & small letters",
    glyph: "🦈",
    route: "/play/feed-the-shark",
    colors: { bg: "#D4EEFF", border: "#74B9FF", text: "#2980B9" },
  },
  {
    id: "space-letters",
    category: "literacy",
    title: "Space ABC",
    description: "Discover letters among the stars",
    glyph: "🚀",
    route: "/play/space-letters",
    colors: { bg: "#0B1330", border: "#5B7FFF", text: "#FFFFFF" },
  },
  {
    id: "ocean-abc",
    category: "literacy",
    title: "Ocean ABC",
    description: "Build, pop & write letters",
    glyph: "🫧",
    route: "/play/ocean-abc",
    colors: { bg: "#114A70", border: "#6FC7EF", text: "#FFFFFF" },
  },
  {
    id: "ocean-hunt",
    category: "literacy",
    title: "Ocean Hunt",
    description: "Find the missing letter",
    glyph: "\u{1F50E}",
    route: "/play/ocean-hunt",
    colors: { bg: "#0E5A86", border: "#FFD93D", text: "#FFFFFF" },
  },
  {
    id: "pirate-match",
    category: "literacy",
    title: "Pirate Match",
    description: "Match letters to treasures",
    glyph: "\u{1F99C}",
    route: "/play/pirate-match",
    colors: { bg: "#5C3A1C", border: "#E9B44C", text: "#FFFFFF" },
  },
  {
    id: "color-paint",
    category: "cognitive",
    title: "Color & Paint",
    description: "Pick the colour, paint the picture",
    glyph: "🖍️",
    route: "/play/color-paint",
    // Candy Land's card colours — this game lives in that world.
    colors: { bg: "#FFD3E4", border: "#FF9EC4", text: "#C2417A" },
    hidden: true,
  },
  {
    id: "counting-numbers",
    category: "numbers",
    title: "Numbers 1 - 5",
    description: "Count and find the missing numbers",
    glyph: "🔢",
    route: "/play/counting-numbers",
    colors: { bg: "#E6F0A8", border: "#C5DD3A", text: "#4F6A0C" },
    // off the shelf: Number Safari now carries these two puzzles. The game
    // itself stays — Number Safari draws its ants with its art.
    hidden: true,
  },
  {
    id: "door-count",
    category: "numbers",
    title: "Count the Doors",
    description: "Count doors, compare, collect keys",
    glyph: "🚪",
    route: "/play/door-count",
    colors: { bg: "#F0E6D2", border: "#C98A3F", text: "#6B4A1E" },
  },
  {
    id: "number-match",
    category: "numbers",
    title: "Number Match",
    description: "Count the cards, fill the sticker book",
    glyph: "🔟",
    route: "/play/number-match",
    colors: { bg: "#E7DEFA", border: "#9A6CE0", text: "#5F3A9C" },
  },
  {
    id: "shape-match",
    category: "cognitive",
    title: "Shapes & Pictures",
    description: "Fit the shapes, finish the picture",
    glyph: "🔺",
    route: "/play/shape-match",
    colors: { bg: "#D6ECFB", border: "#6FC5F2", text: "#2B6C9C" },
  },
  {
    id: "blend-read",
    category: "literacy",
    title: "Blend & Seek",
    description: "Sound out the word, match the picture",
    glyph: "🔤",
    route: "/play/blend-read",
    colors: { bg: "#DCEEFF", border: "#5FA8D6", text: "#2B6C55" },
  },
  {
    id: "number-safari",
    category: "numbers",
    title: "Number Safari",
    description: "Count the creatures, find the missing number",
    glyph: "🐜",
    route: "/play/number-safari",
    colors: { bg: "#E4F3B8", border: "#9EC624", text: "#42610E" },
  },
  {
    id: "cvc-match",
    category: "literacy",
    title: "Word Site",
    description: "Drag each word onto its picture",
    glyph: "🦺",
    route: "/play/cvc-match",
    colors: { bg: "#FDE7BE", border: "#E8A33D", text: "#7A4E12" },
  },
  {
    id: "sort-it",
    category: "cognitive",
    title: "Sort It",
    description: "Put each thing where it belongs",
    glyph: "🧺",
    route: "/play/sort-it",
    colors: { bg: "#D6EEF9", border: "#6FB6D9", text: "#235D7E" },
  },
  {
    id: "word-quiz",
    category: "literacy",
    title: "Snow Words",
    description: "Tap the word that names the picture",
    glyph: "❄️",
    route: "/play/word-quiz",
    colors: { bg: "#DCEFFA", border: "#6FB6D9", text: "#17465F" },
  },
  {
    id: "math-maze",
    category: "numbers",
    title: "Math Maze",
    description: "Tap the numbers in order to reach the prize",
    glyph: "🧭",
    route: "/play/math-maze",
    colors: { bg: "#EDE4FB", border: "#8E6BE0", text: "#4B2F9A" },
  },
  {
    id: "food-sort",
    category: "cognitive",
    title: "Sorting Food",
    description: "Put each food where its shadow is",
    glyph: "🍎",
    route: "/play/food-sort",
    colors: { bg: "#FDE3EE", border: "#E27AAE", text: "#7A2D58" },
  },
  {
    id: "find-the-mouse",
    category: "cognitive",
    title: "Where Is the Mouse?",
    description: "Find the little mouse hiding",
    glyph: "🐭",
    route: "/play/find-the-mouse",
    colors: { bg: "#FFE1B0", border: "#F09A3E", text: "#9A4E12" },
  },
  {
    id: "sesame-activities",
    category: "cognitive",
    title: "Play Street Pals",
    description: "Colours and snack time with Percy, Ruby and Bo",
    glyph: "🐤",
    route: "/play/sesame-activities",
    colors: { bg: "#CFE8FF", border: "#7FB2E8", text: "#3A5A8A" },
  },
  {
    id: "color-shape-friends",
    category: "cognitive",
    title: "Rainbow Shapes",
    description: "Colours, shapes and a block sorter with Berry",
    glyph: "🔺",
    route: "/play/color-shape-friends",
    colors: { bg: "#E7F6D8", border: "#A8D46A", text: "#4F7A1E" },
  },
  {
    id: "pond-numbers",
    category: "numbers",
    title: "Pond Numbers",
    description: "Quick looks and one more frog",
    glyph: "🐸",
    route: "/play/pond-numbers",
    colors: { bg: "#D8F1FB", border: "#5FB455", text: "#237A4B" },
  },
  {
    id: "jigsaw-fun",
    category: "cognitive",
    title: "Jigsaw Fun",
    description: "Pick a picture, fit the pieces",
    glyph: "🧩",
    route: "/play/jigsaw-fun",
    colors: { bg: "#FFF1DC", border: "#E8912A", text: "#8A5A2E" },
  },
  {
    id: "tangram-town",
    category: "cognitive",
    title: "Tangram Town",
    description: "Seven shapes make a picture",
    glyph: "🔷",
    route: "/play/tangram-town",
    colors: { bg: "#E6EEF8", border: "#6F9BD6", text: "#2E5E9E" },
  },
  {
    id: "on-off",
    category: "cognitive",
    title: "On & Off",
    description: "Put things on, take things off",
    glyph: "🛏️",
    route: "/play/on-off",
    colors: { bg: "#FDEBD3", border: "#E59A4B", text: "#8A4B14" },
  },
  {
    id: "sort-two-ways",
    category: "cognitive",
    title: "Sort Two Ways",
    description: "Sort the same things one way, then another",
    glyph: "🔀",
    route: "/play/sort-two-ways",
    colors: { bg: "#E9E3FB", border: "#8D74DB", text: "#4A2F9A" },
  },
  {
    id: "number-groups",
    category: "numbers",
    title: "Count & Match",
    description: "Count the groups, match the numbers",
    glyph: "🍉",
    route: "/play/number-groups",
    colors: { bg: "#FFF3C4", border: "#E8B321", text: "#7A5A06" },
  },
  {
    id: "number-hunt",
    category: "numbers",
    title: "Number Hunt",
    description: "Spot the numbers and fill the number boxes",
    glyph: "🔎",
    route: "/play/number-hunt",
    colors: { bg: "#E6F1FF", border: "#4F8FE0", text: "#1F4F8F" },
  },
] as const;
